### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by EliasVincent** [EliasVincent/NHPlus-Implementation#2]
Wir brauchen einen Login Mechanismus

Akzeptanzkriterien
A_1: Zugriff auf die Verwaltung der persönlichen Daten der Pflegepatienten ist ausschließlich autorisierten Wohnbereichsleitern gestattet.
✔A_2 Ein Login-Bildschirm erscheint beim Start der Anwendung.
✔A_3 Wohnbereichsleiter müssen sich mit ihren zugewiesenen Benutzerdaten (Benutzername und Passwort) einloggen, um Zugang zum System zu erhalten.
✔A_4 Nach einer erfolgreichen Anmeldung wird der Wohnbereichsleiter direkt zur Verwaltungsoberfläche der persönlichen Daten der Pflegepatienten weitergeleitet.
✔A_5 Im Falle einer fehlerhaften Anmeldung wird eine Fehlermeldung ausgegeben.

Tasks
✔T_1: Erstellen eine Benutzeroberfläche mit Feldern für den Benutzernamen und das Passwort sowie einer Schaltfläche für die Anmeldung.
✔T_2: Sicherstellen, dass der Benutzer beim Starten der Anwendung über SNMP auf den Anmeldebildschirm geleitet wird und dass die Felder für den Benutzernamen und das Kennwort korrekt angezeigt werden.
✔T_3: Entwicklung eines Algorithmus zur Validierung der eingegebenen Anmeldedaten. Wir stellen sicher, dass die Anmeldedaten mit den in der Datenbank gespeicherten Daten verglichen werden und dass der Zugriff nur dann gewährt wird, wenn die Anmeldedaten korrekt sind, andernfalls wird der Zugriff mit Hilfe der Bibliothek java.util.regex.Pattern verweigert
✔T_4: Aktualisierung der Benutzerschnittstelle für Fehlermeldungen
✔T_5: Implementieren einen Mechanismus zur Anzeige von Fehlermeldungen im Falle einer fehlerhaften Authentifizierung. Wenn die Authentifizierung fehlschlägt, setzen wir ein Attribut im HttpServletRequest-Objekt, das eine Fehlermeldung enthält.
✔T_6: Sicherstellen, dass die Fehlermeldungen einfach zu verwenden sind und dem Benutzer klare Anweisungen geben.
✔T_7: Prüfen, ob der Benutzer nach der Anzeige der Fehlermeldung auf dem Anmeldebildschirm bleibt, indem der Fehler in einem speziellen Bereich auf dem Bildschirm angezeigt wird.
✔T_8: Entwickeln eine Umleitung auf die Schnittstelle zur Verwaltung der persönlichen Daten der betreuten Patienten nach erfolgreicher Authentifizierung mit Hilfe der Methode openMainWindow(): Diese Methode zeigt das Hauptfenster der Anwendung unter Verwendung von FXMLLoader und Stage an. 
T_9: Sicherstellung, dass nach erfolgreicher Authentifizierung nur autorisierte Benutzer mit einem Status von 0-Falsch oder 1-Wahr Zugang zur Verwaltungsoberfläche haben.
✔T_10: Sicherstellen, dass der Benutzer auf dem Anmeldebildschirm bleibt, wenn die Authentifizierung fehlschlägt.

> Es wird hier von http responses gesprochen, aber wir haben gar keinen server.

Testfälle
✔TF4_1:
Vorbedingung: Die Anwendung ist gestartet.
Auszuführende Testschritte: Versuche, ohne Anmeldung auf das System zuzugreifen.
Erwartetes Ergebnis: Der Login-Bildschirm wird angezeigt.
✔TF4_2:
Vorbedingung: Gültige Anmeldeinformationen sind eingegeben.
Auszuführende Testschritte: Anmeldung mit gültigen Anmeldeinformationen.
Erwartetes Ergebnis: Der Wohnbereichsleiter gelangt zur Verwaltungsoberfläche der persönlichen Daten der Pflegepatienten.
✔TF4_3:
Vorbedingung: Ungültige Anmeldeinformationen sind eingegeben.
Auszuführende Testschritte: Anmeldung mit ungültigen Anmeldeinformationen.
Erwartetes Ergebnis: Eine Fehlermeldung wird angezeigt und der Benutzer verbleibt auf dem Login-Bildschirm.

**Comment by Soufiane-64** [comment]
i added an "Enter key handling for login fields"

**Comment by EliasVincent** [comment]
Was wir am Ende nicht vergessen düfren: ohne erfolgreichen Login keinen Zugriff auf die Tabellen.
