### ISSUE TITLE
Datenschutz + 10 Jahre Sperrfrist

### ISSUE THREAD

**Issue by EliasVincent** [EliasVincent/NHPlus-Implementation#4]
Diese Aufgabe hängt etwas von den anderen ab. Man kann es sich aber schon mal anschauen. Etwa: wie wird das in der Datenbank und in der GUI gelöst?

# User-Story 

Als Leiter der Pflegeanstalt möchte ich, dass Einträge für Behandlungen und Pflegekräfte eine Sperrfrist von 10 Jahren haben bevor sie gelöscht werden können, um geltende Gesetze zur langfristigen Speicherung von medizinischen Daten einzuhalten. 

## Akzeptanzkriterien 
 
✔A_1:  Die Einträge für Behandlungen und Pflegekräfte sollen in der Benutzeroberfläche als gesperrt markiert werden können. 

✔A_2:  Wenn die Einträge gesperrt sind, dürfen sie nicht vollständig gelöscht werden. 

✔A_3: Wenn Einträge für Pflegekräfte gelöscht werden, sollen zugehörige Behandlungen nicht ebenfalls gelöscht werden. 

✔A_4: Nach 10 Jahren können diese Einträge vollständig gelöscht werden. 

✔A_5: Wenn die Einträge gesperrt sind, dürfen sie nicht weiterverarbeitet werden. 

✔A_6 Wenn die Einträge gesperrt sind, müssen sie als solches gekennzeichnet werden. 

## Tasks 

✔T_1: Die Tabellen für Patienten, Pflegekräfte und Behandlungen in der DB erhalten ein Attribut namens `locked`. Da es in SQLite keinen Boolean Datentyp gibt, wird der gesperrt Wert als 0 (falsch) oder 1 (wahr) gespeichert1. 

✔T_2: In der Benutzeroberfläche wird ein “Sperren” Button hinzugefügt. Beim Klicken dieses Buttons wird das gesperrt Attribut in der DB auf wahr gesetzt. 

✔T_3: Der Löschen Button in der Benutzeroberfläche wird ausgegraut, wenn die Daten seit weniger als 10 Jahren gespeichert sind. 

✔T_4: Die ON DELETE CASCADE Eigenschaften in der Datenbank werden entfernt 

✔T_5: Gesperrte Einträge werden in der Oberfläche gekennzeichnet

✔T_6: Gesperrte Einträge dürfen nicht in Verarbeitungen von Daten genutzt werden 

## Testfälle 

✔TF1_:  

Vorbedingung: Es sind Einträge für Pfleger und Behandlungen vorhanden, die nicht älter als 10 Jahre sind 

Auszuführende Testschritte: Versuchen, die Einträge zu löschen 

Erwartetes Ergebnis: Die Einträge werden nicht gelöscht, der Nutzer wird über die Aufbewahrungsfrist informiert 

✔TF2_: 

Vorbedingung: Es sind Einträge für Pfleger und Behandlungen vorhanden, die auch miteinander verknüpft sind 

Auszuführende Testschritte: Löschen/Sperren eines Pfleger-eintrags 

Erwartetes Ergebnis: Mit dem Pfleger verknüpfte Behandlungen werden nicht gelöscht 

✔TF3_: 

Vorbedingung: Es sind Einträge für Pfleger und Behandlungen vorhanden, die nicht älter als 10 Jahre sind 

Auszuführende Testschritte: Es werden Einträge in der GUI ausgewählt und der “Sperren” Button wird geklickt 

Erwartetes Ergebnis: Die Einträge werden auf “gesperrt gesetzt” und entsprechend dargestellt 

 

✔TF4_: 

Vorbedingung: Es sind Einträge für Pfleger und Behandlungen vorhanden, die älter als 10 Jahre sind 

Auszuführende Testschritte: Versuchen, die Einträge zu löschen. 

Erwartetes Ergebnis: Die Einträge werden vollständig gelöscht.

**Comment by EliasVincent** [comment]
Ich habe in der `Caregiver` GUI in `AllCaregiverController.java` das mit dem sperren schon implementiert.
Wenn locked true ist, wird das Feld grau und man kann nicht mehr den Löschen Button klicken. Für `Treatment` und `Patient` können wir das auch genauso machen

**Comment by EliasVincent** [comment]
> Ich habe in der `Caregiver` GUI in `AllCaregiverController.java` das mit dem sperren schon implementiert. Wenn locked true ist, wird das Feld grau und man kann nicht mehr den Löschen Button klicken. Für `Treatment` und `Patient` können wir das auch genauso machen

Das mit dem Button grau wenn locked ist jetzt überall da ✔

Die jetzige Idee:
- `Caregiver, Treatment, Patient` haben alle ein `datecreated` Feld in der Datenbank.
- Wenn man auf den Löschen Button klickt, und der Unterschied zwischen datecreated und currentdate weniger als 10 Jahre ist, kommt ein Popup wie "Dieser Eintrag hat eine Aufbewahrungsfrist von 10 Jahren. Möchten Sie diesen Eintrag wirklich löschen?" mit Ja und Abbrechen.

**Comment by Soufiane-64** [comment]
Ich habe einen neuen Commit im AllPatientController gepusht. Jetzt kann ein Patient nicht gelöscht werden, wenn die Dauer der Daten weniger als 10 Jahre beträgt, wenn man den Lösch-Button anklickt.

**Comment by Soufiane-64** [comment]
Ich habe einen neuen Commit im AllTreatment und AllCaregiver Controller gepusht. Jetzt kann ein treatment oder ein Caregiver nicht gelöscht werden, wenn die Dauer der Daten weniger als 10 Jahre beträgt, wenn man den Lösch-Button anklickt.

**Comment by EliasVincent** [comment]
Funktioniert alles, sehr gut 🥳
